# Generated by Django 5.2.8 on 2025-11-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivitySpotlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("cta_label", models.CharField(blank=True, max_length=80)),
                ("cta_link", models.URLField(blank=True)),
                ("accent_color", models.CharField(default="#0ea5e9", max_length=10)),
                (
                    "background_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="activities/backgrounds/"
                    ),
                ),
            ],
            options={
                "verbose_name": "قاب فعالیت",
                "verbose_name_plural": "قاب\u200cهای فعالیت",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=150)),
                ("organization", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("highlight_color", models.CharField(default="#7c3aed", max_length=10)),
                ("weight", models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                "verbose_name": "تجربه",
                "verbose_name_plural": "تجربه\u200cها",
                "ordering": ["weight", "-start_date"],
            },
        ),
        migrations.CreateModel(
            name="MetricBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=80)),
                ("value", models.PositiveIntegerField(default=0)),
                ("suffix", models.CharField(blank=True, max_length=20)),
                ("accent_color", models.CharField(default="#f97316", max_length=10)),
                ("icon", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "verbose_name": "شاخص",
                "verbose_name_plural": "شاخص\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Recognition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("issuer", models.CharField(max_length=150)),
                ("year", models.CharField(max_length=10)),
                ("description", models.TextField(blank=True)),
                ("badge_color", models.CharField(default="#10b981", max_length=10)),
            ],
            options={
                "verbose_name": "موفقیت",
                "verbose_name_plural": "موفقیت\u200cها",
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("level", models.PositiveSmallIntegerField(default=80)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("ai", "هوش مصنوعی"),
                            ("backend", "بک\u200cاند"),
                            ("frontend", "فرانت\u200cاند"),
                            ("devops", "دواپس"),
                            ("soft", "مهارت نرم"),
                        ],
                        default="ai",
                        max_length=20,
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=100)),
                ("accent_color", models.CharField(default="#f97316", max_length=10)),
            ],
            options={
                "verbose_name": "مهارت",
                "verbose_name_plural": "مهارت\u200cها",
                "ordering": ["-level"],
            },
        ),
    ]
