# Generated by Django 5.2.8 on 2025-11-19 18:53

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PostCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("slug", models.SlugField(blank=True, max_length=120, unique=True)),
                ("description", models.TextField(blank=True)),
                ("accent_color", models.CharField(default="#ff5d8f", max_length=10)),
            ],
            options={
                "verbose_name": "دسته\u200cبندی بلاگ",
                "verbose_name_plural": "دسته\u200cبندی\u200cهای بلاگ",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="blog/hero/"),
                ),
                ("cover_tone", models.CharField(default="#312e81", max_length=10)),
                ("summary", models.TextField(max_length=400)),
                ("content", ckeditor.fields.RichTextField()),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="با کاما جدا کنید", max_length=250
                    ),
                ),
                ("reading_time", models.PositiveSmallIntegerField(default=5)),
                ("author_name", models.CharField(default="احسان لک", max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "پیش\u200cنویس"),
                            ("published", "منتشر شده"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("featured", models.BooleanField(default=False)),
                ("seo_description", models.CharField(blank=True, max_length=160)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="blog.postcategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "پست",
                "verbose_name_plural": "پست\u200cها",
                "ordering": ["-published_at"],
            },
        ),
        migrations.CreateModel(
            name="PostImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="blog/gallery/")),
                ("caption", models.CharField(blank=True, max_length=120)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gallery",
                        to="blog.post",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر پست",
                "verbose_name_plural": "تصاویر پست",
            },
        ),
    ]
