# Generated by Django 5.2.8 on 2025-11-19 18:53

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("slug", models.SlugField(blank=True, max_length=160, unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=100)),
                ("accent_color", models.CharField(default="#f97316", max_length=10)),
            ],
            options={
                "verbose_name": "دسته\u200cبندی دوره",
                "verbose_name_plural": "دسته\u200cبندی\u200cهای دوره",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=240, unique=True)),
                ("summary", models.TextField(max_length=500)),
                ("description", ckeditor.fields.RichTextField()),
                (
                    "hero_image",
                    models.ImageField(blank=True, null=True, upload_to="courses/hero/"),
                ),
                ("featured_video_url", models.URLField(blank=True)),
                ("duration", models.CharField(default="10 ساعت", max_length=60)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("intro", "مقدماتی"),
                            ("intermediate", "میان\u200cرده"),
                            ("advanced", "پیشرفته"),
                        ],
                        default="intro",
                        max_length=20,
                    ),
                ),
                ("price", models.PositiveIntegerField(default=0, help_text="به تومان")),
                ("include_certificate", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("published", models.BooleanField(default=True)),
                ("accent_color", models.CharField(default="#a855f7", max_length=10)),
                ("syllabus_outline", models.TextField(blank=True)),
                ("display_order", models.PositiveSmallIntegerField(default=1)),
                ("seo_description", models.CharField(blank=True, max_length=160)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="courses.coursecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "دوره",
                "verbose_name_plural": "دوره\u200cها",
                "ordering": ["display_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="CourseResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("file", models.FileField(upload_to="courses/resources/")),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("pdf", "PDF"),
                            ("doc", "Word"),
                            ("image", "تصویر"),
                            ("video", "ویدیو"),
                            ("other", "سایر"),
                        ],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("is_downloadable", models.BooleanField(default=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "verbose_name": "منبع دوره",
                "verbose_name_plural": "منابع دوره",
            },
        ),
    ]
